<?php

namespace Database\Seeders;

use App\Models\Gemstone;
use Illuminate\Database\Seeder;

class GemstoneSeeder extends Seeder
{
    public function run(): void
    {
        // Remove existing gemstone products so seed data can be re-run safely.
        Gemstone::withTrashed()->forceDelete();

        $gemstones = [
            [
                'title' => 'Colombian Emerald 2.10 ct',
                'slug' => 'colombian-emerald-2-10ct',
                'gem_type' => 'Emerald',
                'short_description' => 'Vivid green emerald with transparent clarity and GIA certification.',
                'description' => 'A premium Colombian emerald selected for its saturated hue, balanced clarity, and excellent transparency. Each gemstone is independently certified and inspected for integrity before listing.',
                'symbolic_meaning' => 'Traditionally associated with renewal and harmony in many cultures. Symbolic meanings are belief-based and not guaranteed.',
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 6200.00,
                'certificate_lab' => 'GIA',
                'certificate_number' => 'GIA 1452789901',
                'certificate_url' => 'https://www.gia.edu/report-check?reportno=1452789901',
                'treatment' => 'Minor oil (disclosed)',
                'origin' => 'Colombia',
                'carat' => 2.10,
                'color' => 'Vivid Green',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald cut',
                'shape' => 'Octagon',
                'meta_title' => 'Colombian Emerald 2.10 ct | Natural Gem',
                'meta_description' => 'Certified Colombian emerald with full disclosure, GIA report, and transparent sourcing.',
                'is_featured' => true,
            ],
            [
                'title' => 'Sri Lankan Sapphire 1.85 ct',
                'slug' => 'sri-lankan-sapphire-1-85ct',
                'gem_type' => 'Sapphire',
                'short_description' => 'Royal blue sapphire with IGI certification and no diffusion treatment.',
                'description' => 'A refined Sri Lankan sapphire chosen for its rich blue tone and well-proportioned cut. Certification and treatment disclosure are provided with every purchase.',
                'symbolic_meaning' => 'Traditionally linked to wisdom and focus. Symbolic meanings are cultural interpretations and do not imply outcomes.',
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 4800.00,
                'certificate_lab' => 'IGI',
                'certificate_number' => 'IGI 33J987654',
                'certificate_url' => 'https://www.igi.org/reports/verify-your-report',
                'treatment' => 'Heat treated (standard, disclosed)',
                'origin' => 'Sri Lanka',
                'carat' => 1.85,
                'color' => 'Royal Blue',
                'clarity' => 'VS',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Sri Lankan Sapphire 1.85 ct | Natural Gem',
                'meta_description' => 'Certified Sri Lankan sapphire with transparent treatment disclosure and IGI report.',
                'is_featured' => true,
            ],
            [
                'title' => 'Mozambique Ruby 1.20 ct',
                'slug' => 'mozambique-ruby-1-20ct',
                'gem_type' => 'Ruby',
                'short_description' => 'Deep red ruby with GIA certification and full disclosure.',
                'description' => 'A carefully selected Mozambique ruby offering rich saturation and balanced proportions. Full certification and treatment disclosure are included.',
                'symbolic_meaning' => 'Traditionally associated with vitality and courage. Symbolic meanings are cultural beliefs and not guarantees.',
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 3900.00,
                'certificate_lab' => 'GIA',
                'certificate_number' => 'GIA 6421987702',
                'certificate_url' => 'https://www.gia.edu/report-check?reportno=6421987702',
                'treatment' => 'Heat treated (disclosed)',
                'origin' => 'Mozambique',
                'carat' => 1.20,
                'color' => 'Deep Red',
                'clarity' => 'VS',
                'cut' => 'Cushion',
                'shape' => 'Cushion',
                'meta_title' => 'Mozambique Ruby 1.20 ct | Natural Gem',
                'meta_description' => 'Certified Mozambique ruby with full treatment disclosure and GIA report.',
                'is_featured' => true,
            ],
            [
                'title' => 'Tanzanite 3.05 ct',
                'slug' => 'tanzanite-3-05ct',
                'gem_type' => 'Tanzanite',
                'short_description' => 'Trichroic tanzanite with excellent cut and IGI certification.',
                'description' => 'A vivid tanzanite selected for strong blue-violet color and premium cut. Documentation includes certification and treatment details.',
                'symbolic_meaning' => 'Traditionally associated with creativity and calm. Symbolic meaning is belief-based.',
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2600.00,
                'certificate_lab' => 'IGI',
                'certificate_number' => 'IGI 44H556677',
                'certificate_url' => 'https://www.igi.org/reports/verify-your-report',
                'treatment' => 'Heat treated (standard, disclosed)',
                'origin' => 'Tanzania',
                'carat' => 3.05,
                'color' => 'Blue-Violet',
                'clarity' => 'VVS',
                'cut' => 'Pear',
                'shape' => 'Pear',
                'meta_title' => 'Tanzanite 3.05 ct | Natural Gem',
                'meta_description' => 'Certified tanzanite with transparent treatment disclosure and IGI report.',
                'is_featured' => false,
            ],
            [
                'title' => 'Canadian Amethyst 4.00 ct',
                'slug' => 'canadian-amethyst-4-00ct',
                'gem_type' => 'Amethyst',
                'short_description' => 'Rich purple amethyst with ethical Canadian sourcing.',
                'description' => 'A locally sourced Canadian amethyst featuring a deep purple tone and excellent clarity. Ideal for fine jewelry settings.',
                'symbolic_meaning' => 'Traditionally linked to balance and mindfulness. Symbolic meanings are cultural interpretations.',
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 850.00,
                'certificate_lab' => 'In-house',
                'certificate_number' => 'NG-AM-2024-04',
                'certificate_url' => null,
                'treatment' => 'None disclosed',
                'origin' => 'Canada',
                'carat' => 4.00,
                'color' => 'Deep Purple',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Canadian Amethyst 4.00 ct | Natural Gem',
                'meta_description' => 'Ethically sourced Canadian amethyst with transparent disclosure.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 2.18 ct',
                'slug' => 'bi-color-sapphire-cg699',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with radiant cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 5100.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 2.18,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Radiant',
                'shape' => 'Radiant',
                'meta_title' => 'Montana Bi-Color Sapphire 2.18 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 2.18 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 1.36 ct',
                'slug' => 'bi-color-sapphire-cg471',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 3650.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 1.36,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Montana Bi-Color Sapphire 1.36 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 1.36 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 1.22 ct',
                'slug' => 'bi-color-sapphire-s9246',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 3400.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 1.22,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Montana Bi-Color Sapphire 1.22 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 1.22 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 0.92 ct',
                'slug' => 'bi-color-sapphire-cg625',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2850.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 0.92,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Montana Bi-Color Sapphire 0.92 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 0.92 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 0.89 ct',
                'slug' => 'bi-color-sapphire-cg354',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with cushion cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2800.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 0.89,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Cushion',
                'shape' => 'Cushion',
                'meta_title' => 'Montana Bi-Color Sapphire 0.89 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 0.89 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 0.62 ct',
                'slug' => 'bi-color-sapphire-cg679',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2300.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 0.62,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Montana Bi-Color Sapphire 0.62 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 0.62 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 0.60 ct',
                'slug' => 'bi-color-sapphire-s9282',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2300.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 0.60,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Montana Bi-Color Sapphire 0.60 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 0.60 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Montana Bi-Color Sapphire 0.54 ct',
                'slug' => 'bi-color-sapphire-cg726',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Montana, USA with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2150.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Montana, USA',
                'carat' => 0.54,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Montana Bi-Color Sapphire 0.54 ct | Natural Gem',
                'meta_description' => 'Montana Bi-Color Sapphire 0.54 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Madagascar Bi-Color Sapphire 0.65 ct',
                'slug' => 'bi-color-sapphire-s7699',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Madagascar with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 2350.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Madagascar',
                'carat' => 0.65,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Madagascar Bi-Color Sapphire 0.65 ct | Natural Gem',
                'meta_description' => 'Madagascar Bi-Color Sapphire 0.65 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 13.97 ct',
                'slug' => 'bi-color-sapphire-s6409',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 26350.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 13.97,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 13.97 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 13.97 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 9.06 ct',
                'slug' => 'bi-color-sapphire-s6796',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with cushion cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 17500.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 9.06,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Cushion',
                'shape' => 'Cushion',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 9.06 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 9.06 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 7.32 ct',
                'slug' => 'bi-color-sapphire-s8175',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 14400.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 7.32,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 7.32 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 7.32 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 7.12 ct',
                'slug' => 'bi-color-sapphire-s11328',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 14000.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 7.12,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 7.12 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 7.12 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 7.00 ct',
                'slug' => 'bi-color-sapphire-s17038',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 13800.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 7.00,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 7.00 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 7.00 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 6.90 ct',
                'slug' => 'bi-color-sapphire-s11345',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 13600.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 6.90,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 6.90 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 6.90 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 5.43 ct',
                'slug' => 'bi-color-sapphire-s22191',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 10950.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 5.43,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 5.43 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 5.43 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 5.19 ct',
                'slug' => 'bi-color-sapphire-s11721',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 10550.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 5.19,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 5.19 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 5.19 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 4.86 ct',
                'slug' => 'bi-color-sapphire-cg913',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with asscher cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 9950.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 4.86,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Asscher',
                'shape' => 'Asscher',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 4.86 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 4.86 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 4.16 ct',
                'slug' => 'bi-color-sapphire-s7475',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with oval cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 8700.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 4.16,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Oval',
                'shape' => 'Oval',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 4.16 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 4.16 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 4.08 ct',
                'slug' => 'bi-color-sapphire-s20266',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with fancy cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 8550.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 4.08,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Fancy',
                'shape' => 'Fancy',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 4.08 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 4.08 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 3.70 ct',
                'slug' => 'bi-color-sapphire-s9210',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 7850.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 3.70,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 3.70 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 3.70 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 3.67 ct',
                'slug' => 'bi-color-sapphire-s9394',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with round cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 7800.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Untreated (per source listing; verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 3.67,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Round',
                'shape' => 'Round',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 3.67 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 3.67 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 3.50 ct',
                'slug' => 'bi-color-sapphire-s12180',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with fancy cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 7500.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 3.50,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Fancy',
                'shape' => 'Fancy',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 3.50 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 3.50 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
            [
                'title' => 'Sri Lanka Bi-Color Sapphire 3.26 ct',
                'slug' => 'bi-color-sapphire-s5156',
                'gem_type' => 'Bi-Color Sapphire',
                'short_description' => 'Bi-color sapphire from Sri Lanka (Ceylon) with emerald cut and vivid natural color zoning.',
                'description' => 'Curated bi-color sapphire imagery used with permission for editorial presentation. Documentation and treatment verification are available upon request.',
                'symbolic_meaning' => null,
                'image' => '/images/gemstones/curated/.png',
                'price_cad' => 7050.00,
                'certificate_lab' => null,
                'certificate_number' => null,
                'certificate_url' => null,
                'treatment' => 'Treatment not disclosed (verification available upon request)',
                'origin' => 'Sri Lanka (Ceylon)',
                'carat' => 3.26,
                'color' => 'Bi-Color',
                'clarity' => 'Eye-clean',
                'cut' => 'Emerald Cut',
                'shape' => 'Emerald Cut',
                'meta_title' => 'Sri Lanka Bi-Color Sapphire 3.26 ct | Natural Gem',
                'meta_description' => 'Sri Lanka Bi-Color Sapphire 3.26 ct with transparent sourcing and editorial-grade imagery. Documentation available upon request.',
                'is_featured' => false,
            ],
        ];

        $curatedCycle = [
            '/images/gemstones/curated/emerald-cut.png',
            '/images/gemstones/curated/sapphire-gem.png',
            '/images/gemstones/curated/ruby-cut.png',
            '/images/gemstones/curated/tanzanite-marquise.png',
            '/images/gemstones/curated/amethyst-facet-cut.png',
            '/images/gemstones/curated/diamond-emerald-cut.png',
            '/images/gemstones/curated/ametrine-cut.png',
        ];

        $fallbackByType = [
            'Emerald' => '/images/gemstones/curated/emerald-cut.png',
            'Sapphire' => '/images/gemstones/curated/sapphire-gem.png',
            'Ruby' => '/images/gemstones/curated/ruby-cut.png',
            'Tanzanite' => '/images/gemstones/curated/tanzanite-marquise.png',
            'Amethyst' => '/images/gemstones/curated/amethyst-facet-cut.png',
            'Bi-Color Sapphire' => '/images/gemstones/curated/sapphire-gem.png',
        ];

        foreach ($gemstones as $index => $gemstone) {
            $image = $gemstone['image'] ?? null;
            if (!$image || $image === '/images/gemstones/curated/.png') {
                $image = $fallbackByType[$gemstone['gem_type']] ?? null;
            }
            if (!$image) {
                $image = $curatedCycle[$index % count($curatedCycle)];
            }
            $gemstone['image'] = $image;

            Gemstone::withTrashed()->updateOrCreate(
                ['slug' => $gemstone['slug']],
                array_merge($gemstone, ['deleted_at' => null])
            );
        }
    }
}
