[program:laravel-horizon]
process_name=%(program_name)s
command=php /var/www/naturalgem/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-horizon.log
stopwaitsecs=3600
